<?php
Mage::helper('megamenu')->saveCurrentCategoryIdToSession();
$menuData = Mage::helper('megamenu')->getMenuData();
extract($menuData);
// ---
$txtLoading = '';
$txtMenu = $this->__('Menu');
$xRtl = $_rtl ? ' rtl' : '';
$mgInitContent = echo '
    <div id="megamenu-loading" class="$xRtl">
        <div class="menu">
            <div class="parentMenu menu0">
                <a href="javascript:;">
                    <span>$txtLoading</span>
                </a>
            </div>
        </div>
        <div class="clearBoth"></div>
    </div>
    <div id="megamenu" class="$xRtl" style="display:none;">
        <div class="menu">
            <div class="parentMenu menu0">
                <a href="javascript:;">
                    <span>$txtLoading</span>
                </a>
            </div>
        </div>
        <div class="clearBoth"></div>
    </div>
    <div id="megamenu-mobile" class="$xRtl" style="display:none;">
        <div id="menu-button" onclick="mgMenuButtonToggle()">
            <a href="javascript:void(0);">
                <span>$txtMenu</span>
            </a>
        </div>
        <div id="menu-content" style="display:none;">
            <div id="menu-mobile-loading" class="menu-mobile level0">
                <div class="parentMenu">
                    <a href="javascript:;">
                        <span>$txtLoading</span>
                    </a>
                </div>
            </div>
            <div class="clearBoth"></div>
        </div>
    </div>';
?>
<div class="nav-container" id="mg-nav-container"></div>
<script type="text/javascript">
    //<![CDATA[
    var CUSTOMMENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
    var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo $_popupTopOffset; ?>;
    var CUSTOMMENU_POPUP_DELAY_BEFORE_DISPLAYING = <?php echo $_popupDelayBeforeDisplaying; ?>;
    var CUSTOMMENU_POPUP_DELAY_BEFORE_HIDING = <?php echo $_popupDelayBeforeHiding; ?>;
    var CUSTOMMENU_RTL_MODE = <?php echo $_rtl; ?>;
    var CUSTOMMENU_MOBILE_MENU_WIDTH_INIT = <?php echo $_mobileMenuWidthInit; ?>;
    var mgCustommenuTimerShow = {};
    var mgCustommenuTimerHide = {};
    var mgActiveMenu = null;
    var mgMobileMenuEnabled = <?php echo $_mobileMenuEnabled; ?>;
    var mgMenuAjaxUrl = '<?php echo $_menuAjaxUrl; ?>';
    var mgMoblieMenuAjaxUrl = '<?php echo $_moblieMenuAjaxUrl; ?>';
    var mgPopupMenuContent = '';
    var mgMobileMenuContent = '';
    if ($('mg-nav-container') != undefined) {
        $('mg-nav-container').update(<?php echo Mage::helper('core')->jsonEncode($mgInitContent); ?>);
    }
    <?php if (Mage::getStoreConfig('megamenu/general/ajax_load_content')) : ?>
    mgMegamenuMobileToggle();
    Event.observe(window, 'resize', function() {
        mgMegamenuMobileToggle();
    });
    <?php endif; ?>
    //]]>
</script>

<script type="text/javascript">
    //<![CDATA[
    Event.observe(document, 'dom:loaded', function(){
        $$('.skip-nav').each(function(element) {
            element.observe('click', function(event) {
                mgMenuButtonToggle();
            });
        });
    });
    //]]>
</script>
